"""Constants for the RS-485 sensor node."""

CALIBRATION_PATH = "/config/rs485_sensor_node_cal.json"

STATS_WINDOW_S = 3.0
LOG_INTERVAL_S = 5.0
POLARITY_NORMAL = 0
POLARITY_REVERSED = 1
DATA_RECORD_BYTES = 4
MINMAX_RECORD_BYTES = 6
STD_WINDOW = 100
EVENT_STATE_OFF = 0
EVENT_STATE_ON = 1
TRACE_CHUNK_SAMPLES = 25
VELOCITY_WINDOW_PCT = 20
SENSORS_PER_BANK = 4
SENSOR_VALUE_MAX = 65535
# Calibration frame types (not in photon_rs485 C driver)
FRAME_TYPE_CAL_CMD = ord("K")
FRAME_TYPE_CAL_ACK = ord("k")
CAL_CMD_RESET = 1
CAL_CMD_SAVE = 2
CAL_ACK_OK = 1
CAL_ACK_FAIL = 0
