# Run at build time (see CMakeLists.txt): writes ${OUT} with the git short
# hash of HEAD, "-dirty" appended when firmware/ has uncommitted changes, and
# the build timestamp. Printed by the console banner and `id`, and stored as
# picotool binary info so a board in BOOTSEL can say which build it carries.
# Usage: cmake -DSRC_DIR=<firmware dir> -DOUT=<header path> -P build_id.cmake
set(id "unknown")
find_program(GIT_EXECUTABLE git)
if (GIT_EXECUTABLE)
    execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short=7 HEAD
                    WORKING_DIRECTORY ${SRC_DIR}
                    OUTPUT_VARIABLE hash OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET RESULT_VARIABLE rc)
    if (rc EQUAL 0 AND NOT hash STREQUAL "")
        set(id "${hash}")
        execute_process(COMMAND ${GIT_EXECUTABLE} status --porcelain --untracked-files=no -- .
                        WORKING_DIRECTORY ${SRC_DIR}
                        OUTPUT_VARIABLE dirty ERROR_QUIET)
        if (NOT dirty STREQUAL "")
            string(APPEND id "-dirty")
        endif ()
    endif ()
endif ()
string(TIMESTAMP now "%Y-%m-%d %H:%M")
get_filename_component(out_dir ${OUT} DIRECTORY)
file(MAKE_DIRECTORY ${out_dir})
file(WRITE ${OUT}.tmp
"// Generated by cmake/build_id.cmake on every build. Do not edit or commit.
#ifndef PHOTON_BUILD_ID_H
#define PHOTON_BUILD_ID_H
#define PHOTON_BUILD_ID   \"${id}\"
#define PHOTON_BUILD_DATE \"${now}\"
#endif
")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${OUT}.tmp ${OUT})
file(REMOVE ${OUT}.tmp)
